package week11.st729217.pinpoint.data

import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.UserProfileChangeRequest
import kotlinx.coroutines.tasks.await
import week11.st729217.pinpoint.addFriendFeature.model.Users
import week11.st729217.pinpoint.addFriendFeature.repository.UserRepository

class AuthRepository(
    private val auth: FirebaseAuth = FirebaseAuth.getInstance(),
    //add the UserRepository here so we can save data
    private val userRepository: UserRepository = UserRepository()
) {
    suspend fun register(email: String, password: String, displayName: String?): Result<Unit> {
        return try {
            auth.createUserWithEmailAndPassword(email, password).await()
            val user = auth.currentUser

            if (displayName != null && user != null) {
                val updates = UserProfileChangeRequest.Builder()
                    .setDisplayName(displayName).
                    build()
                user.updateProfile(updates).await()
            }

            // Step 3: Create the User Object for Firestore
            // We use the UID generated by Step 1
            val newUser = Users(
                uid = user?.uid,
                name = user?.displayName,
                email = user?.email,
                shareStatus = false // Default
            )

            // We wait for this to finish. If this fails, the whole function fails.
            val dbResult = userRepository.saveUserToFirestore(newUser)

            if (dbResult.isSuccess) {
                Result.success(Unit)
            } else {
                // Optional: If DB save fails, you might want to delete the Auth user
                // to prevent "ghost" accounts, but for now, we just return failure.
                Result.failure(dbResult.exceptionOrNull() ?: Exception("Database save failed"))
            }
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun login(email: String, password: String): Result<Unit> {
        return try {
            auth.signInWithEmailAndPassword(email, password).await()
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    fun signOut() {
        auth.signOut()
    }
}
